blank_issues_enabled: true
contact_links:
  - name: 3. Contact our c:geo support team
    url: https://www.cgeo.org/support
    about: If you have questions regarding the usage of c:geo you should contact our support team by mail instead. Click to open our support page for more information.
